Prepocessing
Preprocessing adalah tahap pra-pemrosesan data sebelum data digunakan untuk analisis, pemodelan, atau pelatihan algoritma machine learning. Tujuannya adalah agar data menjadi bersih, konsisten, dan siap dipakai, sehingga model bisa bekerja lebih baik dan hasilnya lebih akurat.

Mengapa Preprocessing Penting?
Data mentah biasanya tidak rapi (ada nilai kosong, duplikasi, outlier, format berbeda).

Algoritma machine learning sensitif terhadap skala, tipe data, dan distribusi data.

Preprocessing membuat data:

Lebih seragam

Lebih mudah dipahami oleh algoritma

Mengurangi bias atau error

Langkah-langkah Preprocessing (umum)
Data Cleaning (Pembersihan Data)

Menghapus duplikasi data

Menangani nilai kosong (missing value)

Menghapus atau memperlakukan outlier

Data Transformation (Transformasi Data)

Normalisasi atau standarisasi skala (contoh: semua fitur punya skala 0â€“1 atau rata-rata 0, standar deviasi 1)

Encoding data kategorikal ke bentuk numerik (contoh: Male=0, Female=1)

Data Reduction (Reduksi Data)

Mengurangi dimensi (misalnya PCA)

Menghapus fitur yang tidak relevan

# 1. Pengumpulan Data

In [1]:
import pandas as pd
from sqlalchemy import create_engine

MYSQL_HOST = "database-aplikasi-saya-mysql-muhammadazhariii1209-4402.j.aivencloud.com"
MYSQL_PORT = 14467
MYSQL_USER = "avnadmin"
MYSQL_PASSWORD = "AVNS_-m75fnNFJLYQ3JbqMc4"
MYSQL_DATABASE = "defaultdb"

PG_HOST = "database-aplikasi-saya-muhammadazhariii1209-4402.j.aivencloud.com"
PG_PORT = 14467
PG_USER = "avnadmin"
PG_PASSWORD = "AVNS_cAY9-ITh6Sy3eujURVI"
PG_DATABASE = "defaultdb"

mysql_engine = create_engine(
    f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"
)

pg_engine = create_engine(
    f"postgresql+psycopg2://{PG_USER}:{PG_PASSWORD}@{PG_HOST}:{PG_PORT}/{PG_DATABASE}"
)

mysql_query = "SELECT * FROM iris_mysql;"
df_mysql = pd.read_sql(mysql_query, mysql_engine)

pg_query = "SELECT * FROM iris_postgre;"
df_postgres = pd.read_sql(pg_query, pg_engine)

print("Data dari MySQL:")
print(df_mysql.head())

print("\nData dari PostgreSQL:")
print(df_postgres.head())

Data dari MySQL:
   id        Class  petal length  petal width
0   1  Iris-setosa           1.4          0.2
1   2  Iris-setosa           1.4          0.2
2   3  Iris-setosa           1.3          0.2
3   4  Iris-setosa           1.5          0.2
4   5  Iris-setosa           1.4          0.2

Data dari PostgreSQL:
   id        Class  sepal length  sepal width
0   1  Iris-setosa           5.1          3.5
1   2  Iris-setosa           4.9          3.0
2   3  Iris-setosa           4.7          3.2
3   4  Iris-setosa           4.6          3.1
4   5  Iris-setosa           5.0          3.6

In [2]:
import os
mysql_query = "SELECT * FROM iris_mysql;"
df_mysql = pd.read_sql(mysql_query, mysql_engine)

pg_query = "SELECT * FROM iris_postgre;"
df_postgres = pd.read_sql(pg_query, pg_engine)

# Print hasil query
print("Data dari MySQL:")
print(df_mysql.head())

print("\n Data dari PostgreSQL:")
print(df_postgres.head())

#Menghapus file yang di upload sebelumnya
if os.path.exists(".env"):
    os.remove(".env")


df_combined = pd.merge(df_postgres, df_mysql.drop(columns=['Class']), on="id", how="inner")

print("\nData gabungan:")
print(df_combined)

Data dari MySQL:
   id        Class  petal length  petal width
0   1  Iris-setosa           1.4          0.2
1   2  Iris-setosa           1.4          0.2
2   3  Iris-setosa           1.3          0.2
3   4  Iris-setosa           1.5          0.2
4   5  Iris-setosa           1.4          0.2

 Data dari PostgreSQL:
   id        Class  sepal length  sepal width
0   1  Iris-setosa           5.1          3.5
1   2  Iris-setosa           4.9          3.0
2   3  Iris-setosa           4.7          3.2
3   4  Iris-setosa           4.6          3.1
4   5  Iris-setosa           5.0          3.6

Data gabungan:
      id           Class  sepal length  sepal width  petal length  petal width
0      1     Iris-setosa           5.1          3.5           1.4          0.2
1      2     Iris-setosa           4.9          3.0           1.4          0.2
2      3     Iris-setosa           4.7          3.2           1.3          0.2
3      4     Iris-setosa           4.6          3.1           1.5          0.2
4      5     Iris-setosa           5.0          3.6           1.4          0.2
..   ...             ...           ...          ...           ...          ...
145  146  Iris-virginica           6.7          3.0           5.2          2.3
146  147  Iris-virginica           6.3          2.5           5.0          1.9
147  148  Iris-virginica           6.5          3.0           5.2          2.0
148  149  Iris-virginica           6.2          3.4           5.4          2.3
149  150  Iris-virginica           5.9          3.0           5.1          1.8

[150 rows x 6 columns]